export enum Offsets {
    ServerConnectionUpdate = 0x45fa98,
    HasConnectFailed = Process.pointerSize,
    State = 16,
    GetMessageType = Process.pointerSize * 5,
    Destruct = Process.pointerSize * 7,
    Decode = 3 * Process.pointerSize,
    MessageManagerReceiveMessage = 0x45318c,
    HomePageStartGame = 0x58aba8,
    MessagingSend = 0x9b05fc,
    NativeFontFormatString = 0x0,
    MessageManagerInstance = 0xda52e4,
    CreateMessageByType = 0x6f1b90,
    LogicLaserMessageFactory = 0xce0a9a,
    Version = 84,
    ByteStream = 4,
    PayloadSize = 20,
    PayloadPtr = 44,
    OperatorNew = 0xcb6380,
    StringConstructor = 0x9c428c,
    IsDev = 0x5ecbc8
}