export enum Offsets {
    ServerConnectionUpdate = 0x45fa98,
    HasConnectFailed = Process.pointerSize,
    State = 16,
    GetMessageType = Process.pointerSize * 5,
    Destruct = Process.pointerSize * 7,
    Decode = 3 * Process.pointerSize,
    MessageManagerReceiveMessage = 0x0,
    HomePageStartGame,
    MessagingSend,
    NativeFontFormatString,
    MessageLength,
    ByteStream,
    MessageManagerInstance,
    CreateMessageByType,
    LogicLaserMessageFactory,
    Version,
    PayloadSize,
    PayloadPtr,
    OperatorNew,
    StringConstructor,
}